SimplesMed/Controllers/AgendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SimplesMed.Model;

namespace SimplesMed.Controllers
{
    public class AgendaController : Controller
    {
        Services.SettingService.ISetting Setting;

        public AgendaController(Services.SettingService.ISetting setting)
        {
            Setting = setting;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetAgendamentosCalendario()
        {
            try
            {
                HttpClient httpClient = new HttpClient();
                var uri = String.Format("{0}schedules?expand=patient", Setting.URLBASE);
                var responde = await httpClient.GetAsync(uri);

                var result = JsonConvert.DeserializeObject<List<Agendamento>>(await responde.Content.ReadAsStringAsync());

                List<Calendario> calendarios = new List<Calendario>();
                foreach (var i in result)
                {
                    Calendario calendario = new Calendario();
                    if (i.status == "sheduled")
                        calendario.color = "#005eff";
                    if (i.status == "completed")
                        calendario.color = "#00ff00";
                    if (i.status == "canceled")
                        calendario.color = "#ff0500";
                    if (i.status == "awaiting")
                        calendario.color = "#ffea00";

                    calendario.id = i.id;
                    calendario.start = DateTime.Parse(i.date).ToString("s");
                    calendario.end = DateTime.Parse(i.date).AddMinutes(30).ToString("s");
                    if (i.patient != null)
                    {
                        calendario.title = i.patient.name;
                    }
                    else
                    {
                        calendario.title = "Bloqueio";
                    }

                    calendarios.Add(calendario);
                }
                return Json(calendarios.ToArray());
            }
            catch (Exception)
            {
                return null;
            }            
        }

    }
}

SimplesMed/Controllers/ExameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SimplesMed.Model;
using SimplesMed.Services.ExameService;

namespace SimplesMed.Controllers
{
    public class ExameController : Controller
    {
        IExame Exame;
        public ExameController(IExame exame)
        {
            Exame = exame;
        }
        public async  Task<IActionResult> Index()
        {

            return View( await Exame.GetAll());
        }

        public async Task<IActionResult> Salvar([FromBody] Exam exam)
        {            
            return Json(await Exame.Save(exam));
        }


    }
}

SimplesMed/Controllers/PacienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SimplesMed.Model;
using SimplesMed.Services.PacienteService;

namespace SimplesMed.Controllers
{
    public class PacienteController : Controller
    {
        IPaciente Paciente;
        public PacienteController(IPaciente paciente)
        {
            Paciente = paciente;
        }
        public async Task<IActionResult> Index()
        {
            return View(await Paciente.GetAll());
        }

        public async Task<IActionResult> Salvar([FromBody] Pacient paciente)
        {
            if (paciente.id == null)
            {
                paciente.id = Guid.NewGuid().ToString();
                return Json(await Paciente.Save(paciente));
            }
            else
            {
                return Json(await Paciente.Update(paciente));
            }
        }
    }
}

SimplesMed/Controllers/UnidadeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SimplesMed.Model;
using SimplesMed.Services.UnidadeService;

namespace SimplesMed.Controllers
{
    public class UnidadeController : Controller
    {
        private IUnidade Unidade;
        public UnidadeController(IUnidade unidade)
        {
            Unidade = unidade;
        }
        public async Task<IActionResult> Index()
        {
            var result = await Unidade.GetAll();
            return View(result);
        }

        public async Task<IActionResult> Salvar([FromBody] Unidades unidades)
        {
            if (unidades.id == null)
            {
                unidades.id = Guid.NewGuid().ToString();
                return Json(await Unidade.Save(unidades));
            }
            else
            {
                return Json(await Unidade.Update(unidades));
            }
        }
    }
}

SimplesMed/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimplesMed</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="@Url.Action("Index","Home")">SimpleMed</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="@Url.Action("Index","Home")">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="@Url.Action("Index","Agenda")">Agenda</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Cadastros</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="@Url.Action("Index","Paciente")">Paciente</a>
                                <a class="dropdown-item" href="@Url.Action("Index","Profissional")">Profissional</a>
                                <a class="dropdown-item" href="@Url.Action("Index","Laboratorio")">Laboratorio</a>
                                <a class="dropdown-item" href="@Url.Action("Index","Unidade")">Unidade Atendimento</a>

                            </div>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="@Url.Action("Index","Exame")">Exames</a>
                        </li>
                      

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SimplesMed - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.5.0/knockout-min.js"></script>
    <script src="https://kit.fontawesome.com/8230d65834.js" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>
<script>
    var screenModel = new ScreenModel();
    ko.applyBindings(screenModel);
</script>

SimplesMed/Pages/Shared/_LoginLayout.cshtml
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimplesMed</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        body {
            background-image: url("~/imagens/background.jpeg");
            background-color: #17a2b8;
        }
    </style>
</head>

<body >
    <div>
        @RenderBody()
    </div>
</body>

</html>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/lib/knockout/knockout.js"></script>

@RenderSection("Scripts", required: false)
<script>
    var screenModel = new ScreenModel();
    ko.applyBindings(screenModel);
</script>